name: music_app
description: "A music player app which let you stream and download music from youtube music"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.4
  audio_video_progress_bar: ^2.0.3
  youtube_explode_dart: ^2.5.2
  google_fonts: ^6.3.1
  provider: ^6.1.5
  dart_ytmusic_api: ^1.2.1
  http: ^1.5.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  path: ^1.9.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4
  launcher_name: ^1.0.2
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png" # path to your main icon
  adaptive_icon_background: "#ffffff" # (optional) background for Android adaptive icons
  adaptive_icon_foreground: "icon.png" # (optional) foreground layer

launcher_name:
  default: "Just PLAY"