name: music_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.4
  audio_video_progress_bar: ^2.0.3
  youtube_explode_dart: ^2.5.2
  google_fonts: ^6.3.1
  provider: ^6.1.5
  dart_ytmusic_api: ^1.2.1
  http: ^1.5.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  path: ^1.9.0
  bottom_sheet_bar: ^2.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
